-- SYSTEM 08 TASK 8.3: new AuditAction taxonomy entry, same convention V098/V099 used to extend
-- this CHECK constraint (kept in sync with enums/AuditAction.java by hand).
ALTER TABLE unified_audit_events
    DROP CONSTRAINT IF EXISTS chk_unified_audit_events_action;
ALTER TABLE unified_audit_events
    ADD CONSTRAINT chk_unified_audit_events_action CHECK (action IN (
        -- Auth
        'AUTH_LOGIN_SUCCESS', 'AUTH_LOGIN_FAILED', 'AUTH_LOGOUT',
        'AUTH_PASSWORD_CHANGED', 'AUTH_PASSWORD_RESET_REQUESTED',
        'AUTH_PASSWORD_RESET_COMPLETED', 'AUTH_MFA_ENABLED', 'AUTH_MFA_DISABLED',
        'AUTH_SESSION_REVOKED', 'AUTH_TOKEN_THEFT_DETECTED', 'AUTH_UNAUTHORIZED',
        -- RBAC
        'ROLE_GRANTED', 'ROLE_REVOKED', 'PERMISSION_GRANTED', 'PERMISSION_REVOKED',
        'ACCESS_DENIED',
        -- User lifecycle
        'USER_CREATED', 'USER_UPDATED', 'USER_DEACTIVATED', 'USER_REACTIVATED',
        'USER_ROLE_CHANGED', 'USER_DATA_ERASED',
        -- Platform admin
        'ORG_SUSPENDED', 'ORG_REACTIVATED', 'ORG_TRIAL_EXTENDED', 'ORG_DELETED', 'ORG_PURGED',
        'ORG_MFA_POLICY_CHANGED',
        'ENTITLEMENT_GRANTED', 'ENTITLEMENT_REVOKED', 'CROSS_ORG_ACCESS',
        'FEATURE_FLAG_CHANGED',
        -- Billing
        'SUBSCRIPTION_CREATED', 'SUBSCRIPTION_CHANGED', 'SUBSCRIPTION_CANCELLED',
        'INVOICE_PAYMENT_FAILED', 'REFUND_CREATED', 'BILLING_OVERRIDE_APPLIED',
        -- Bulk-import lifecycle
        'FILE_UPLOAD_INITIATED', 'FILE_PROCESSING_STARTED',
        'FILE_PROCESSING_COMPLETED', 'FILE_PROCESSING_PARTIALLY_FAILED',
        'FILE_PROCESSING_FAILED', 'FILE_UPLOAD_DELETED',
        -- Reports & export
        'REPORT_GENERATED', 'REPORT_EXPORTED', 'DATA_EXPORTED', 'AUDIT_LOG_EXPORTED'
    ));
