package com.recoverpro.server.enums;

public enum NotificationType {

    PLATFORM_ORG_ONBOARDED,
    PLATFORM_SYSTEM_OUTAGE,
    PLATFORM_SUSPICIOUS_LOGIN,
    PLATFORM_MASS_DATA_EXPORT,

    ORG_CALLING_HOURS_VIOLATION,
    ORG_FREQUENCY_CAP_BREACH,
    ORG_SOS_TRIGGERED,
    ORG_HIGH_VALUE_PTP_BROKEN,
    ORG_ALLOCATION_UPLOAD_DONE,
    ORG_APPROVAL_PENDING_OVERDUE,
    ORG_PAYMENT_FAILED,
    ORG_PAYMENT_RECOVERED,
    ORG_SUBSCRIPTION_CANCELLED,
    ORG_TRIAL_EXPIRING_SOON,
    ORG_TRIAL_EXPIRED,

    TL_TEAM_SOS,
    TL_APPROVAL_REQUESTED,
    TL_VISIT_FAILED,
    TL_CASES_UNASSIGNED,

    FO_CASE_ASSIGNED,
    FO_VISIT_ASSIGNED,
    FO_DISPATCH_READY,
    FO_PTP_EXPIRING_SOON,
    FO_PTP_BROKEN,
    FO_COLLECTION_RECORDED,
    FO_SHIFT_STARTING,
    FO_DO_NOT_CONTACT,

    APPROVAL_DECIDED,
    REPORT_READY,
    USER_REQUEST_DECIDED,
}
